services:
  - type: web
    name: atm-messina-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn atm_messina_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5001

